import pytest

from counterweight.events import AnyEvent, KeyPressed
from counterweight.keys import Key, vt_inputs


@pytest.mark.parametrize(
    "buffer, expected",
    [
        # single characters, raw
        ("f", [KeyPressed(key="f")]),
        ("foo", [KeyPressed(key="f"), KeyPressed(key="o"), KeyPressed(key="o")]),
        # single bytes, transformed
        ("\x1b", [KeyPressed(key=Key.Escape)]),
        ("\t", [KeyPressed(key=Key.Tab)]),
        ("\n", [KeyPressed(key=Key.Enter)]),
        (" ", [KeyPressed(key=Key.Space)]),
        ("\x00", [KeyPressed(key=Key.ControlSpace)]),
        ("\x01", [KeyPressed(key=Key.ControlA)]),
        ("\x02", [KeyPressed(key=Key.ControlB)]),
        ("\x03", [KeyPressed(key=Key.ControlC)]),
        ("\x04", [KeyPressed(key=Key.ControlD)]),
        ("\x05", [KeyPressed(key=Key.ControlE)]),
        ("\x06", [KeyPressed(key=Key.ControlF)]),
        ("\x07", [KeyPressed(key=Key.ControlG)]),
        ("\x08", [KeyPressed(key=Key.Backspace)]),
        ("\x0B", [KeyPressed(key=Key.ControlK)]),
        ("\x0C", [KeyPressed(key=Key.ControlL)]),
        ("\x0E", [KeyPressed(key=Key.ControlN)]),
        ("\x0F", [KeyPressed(key=Key.ControlO)]),
        ("\x10", [KeyPressed(key=Key.ControlP)]),
        ("\x11", [KeyPressed(key=Key.ControlQ)]),
        ("\x12", [KeyPressed(key=Key.ControlR)]),
        ("\x13", [KeyPressed(key=Key.ControlS)]),
        ("\x14", [KeyPressed(key=Key.ControlT)]),
        ("\x15", [KeyPressed(key=Key.ControlU)]),
        ("\x16", [KeyPressed(key=Key.ControlV)]),
        ("\x17", [KeyPressed(key=Key.ControlW)]),
        ("\x18", [KeyPressed(key=Key.ControlX)]),
        ("\x19", [KeyPressed(key=Key.ControlY)]),
        ("\x1A", [KeyPressed(key=Key.ControlZ)]),
        ("\x7f", [KeyPressed(key=Key.Backspace)]),
        # f1 to f4
        ("\x1bOP", [KeyPressed(key=Key.F1)]),
        ("\x1bOQ", [KeyPressed(key=Key.F2)]),
        ("\x1bOR", [KeyPressed(key=Key.F3)]),
        ("\x1bOS", [KeyPressed(key=Key.F4)]),
        # shift-tab
        ("\x1b[Z", [KeyPressed(key=Key.BackTab)]),
        # CSI lookups
        ("\x1b[A", [KeyPressed(key=Key.Up)]),
        ("\x1b[B", [KeyPressed(key=Key.Down)]),
        ("\x1b[C", [KeyPressed(key=Key.Right)]),
        ("\x1b[D", [KeyPressed(key=Key.Left)]),
        ("\x1b[2~", [KeyPressed(key=Key.Insert)]),
        ("\x1b[3~", [KeyPressed(key=Key.Delete)]),
        ("\x1b[F", [KeyPressed(key=Key.End)]),
        ("\x1b[11~", [KeyPressed(key=Key.F1)]),
        ("\x1b[12~", [KeyPressed(key=Key.F2)]),
        ("\x1b[13~", [KeyPressed(key=Key.F3)]),
        ("\x1b[14~", [KeyPressed(key=Key.F4)]),
        ("\x1b[17~", [KeyPressed(key=Key.F6)]),
        ("\x1b[18~", [KeyPressed(key=Key.F7)]),
        ("\x1b[19~", [KeyPressed(key=Key.F8)]),
        ("\x1b[20~", [KeyPressed(key=Key.F9)]),
        ("\x1b[21~", [KeyPressed(key=Key.F10)]),
        ("\x1b[23~", [KeyPressed(key=Key.F11)]),
        ("\x1b[24~", [KeyPressed(key=Key.F12)]),
        ("\x1b[25~", [KeyPressed(key=Key.F13)]),
        ("\x1b[26~", [KeyPressed(key=Key.F14)]),
        ("\x1b[28~", [KeyPressed(key=Key.F15)]),
        ("\x1b[29~", [KeyPressed(key=Key.F16)]),
        ("\x1b[31~", [KeyPressed(key=Key.F17)]),
        ("\x1b[32~", [KeyPressed(key=Key.F18)]),
        ("\x1b[33~", [KeyPressed(key=Key.F19)]),
        ("\x1b[34~", [KeyPressed(key=Key.F20)]),
        ("\x1b[1;2A", [KeyPressed(key=Key.ShiftUp)]),
        ("\x1b[1;2B", [KeyPressed(key=Key.ShiftDown)]),
        ("\x1b[1;2C", [KeyPressed(key=Key.ShiftRight)]),
        ("\x1b[1;2D", [KeyPressed(key=Key.ShiftLeft)]),
        ("\x1b[1;5A", [KeyPressed(key=Key.ControlUp)]),
        ("\x1b[1;5B", [KeyPressed(key=Key.ControlDown)]),
        ("\x1b[1;5C", [KeyPressed(key=Key.ControlRight)]),
        ("\x1b[1;5D", [KeyPressed(key=Key.ControlLeft)]),
        ("\x1b[1;6A", [KeyPressed(key=Key.ControlShiftUp)]),
        ("\x1b[1;6B", [KeyPressed(key=Key.ControlShiftDown)]),
        ("\x1b[1;6C", [KeyPressed(key=Key.ControlShiftRight)]),
        ("\x1b[3;3~", [KeyPressed(key=Key.AltDelete)]),
        ("\x1b[3;5~", [KeyPressed(key=Key.ControlDelete)]),
        ("\x1b[3;6~", [KeyPressed(key=Key.ControlShiftInsert)]),
    ],
)
def test_vt_input_parsing(buffer: str, expected: list[AnyEvent]) -> None:
    assert vt_inputs.parse(buffer) == expected
