from reprisal.styles import Margin, Style
from reprisal.styles.styles import CellStyle, Color, Text

# Start generated Tailwind colors

text_slate_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f8fafc"))))
text_slate_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f1f5f9"))))
text_slate_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#e2e8f0"))))
text_slate_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#cbd5e1"))))
text_slate_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#94a3b8"))))
text_slate_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#64748b"))))
text_slate_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#475569"))))
text_slate_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#334155"))))
text_slate_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#1e293b"))))
text_slate_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#0f172a"))))
text_slate_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#020617"))))

text_gray_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f9fafb"))))
text_gray_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f3f4f6"))))
text_gray_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#e5e7eb"))))
text_gray_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#d1d5db"))))
text_gray_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#9ca3af"))))
text_gray_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#6b7280"))))
text_gray_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#4b5563"))))
text_gray_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#374151"))))
text_gray_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#1f2937"))))
text_gray_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#111827"))))
text_gray_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#030712"))))

text_zinc_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fafafa"))))
text_zinc_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f4f4f5"))))
text_zinc_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#e4e4e7"))))
text_zinc_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#d4d4d8"))))
text_zinc_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#a1a1aa"))))
text_zinc_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#71717a"))))
text_zinc_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#52525b"))))
text_zinc_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#3f3f46"))))
text_zinc_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#27272a"))))
text_zinc_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#18181b"))))
text_zinc_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#09090b"))))

text_neutral_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fafafa"))))
text_neutral_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f5f5f5"))))
text_neutral_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#e5e5e5"))))
text_neutral_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#d4d4d4"))))
text_neutral_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#a3a3a3"))))
text_neutral_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#737373"))))
text_neutral_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#525252"))))
text_neutral_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#404040"))))
text_neutral_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#262626"))))
text_neutral_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#171717"))))
text_neutral_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#0a0a0a"))))

text_stone_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fafaf9"))))
text_stone_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f5f5f4"))))
text_stone_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#e7e5e4"))))
text_stone_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#d6d3d1"))))
text_stone_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#a8a29e"))))
text_stone_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#78716c"))))
text_stone_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#57534e"))))
text_stone_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#44403c"))))
text_stone_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#292524"))))
text_stone_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#1c1917"))))
text_stone_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#0c0a09"))))

text_red_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fef2f2"))))
text_red_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fee2e2"))))
text_red_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fecaca"))))
text_red_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fca5a5"))))
text_red_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f87171"))))
text_red_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ef4444"))))
text_red_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#dc2626"))))
text_red_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#b91c1c"))))
text_red_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#991b1b"))))
text_red_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#7f1d1d"))))
text_red_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#450a0a"))))

text_orange_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fff7ed"))))
text_orange_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ffedd5"))))
text_orange_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fed7aa"))))
text_orange_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fdba74"))))
text_orange_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fb923c"))))
text_orange_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f97316"))))
text_orange_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ea580c"))))
text_orange_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#c2410c"))))
text_orange_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#9a3412"))))
text_orange_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#7c2d12"))))
text_orange_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#431407"))))

text_amber_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fffbeb"))))
text_amber_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fef3c7"))))
text_amber_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fde68a"))))
text_amber_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fcd34d"))))
text_amber_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fbbf24"))))
text_amber_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f59e0b"))))
text_amber_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#d97706"))))
text_amber_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#b45309"))))
text_amber_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#92400e"))))
text_amber_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#78350f"))))
text_amber_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#451a03"))))

text_yellow_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fefce8"))))
text_yellow_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fef9c3"))))
text_yellow_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fef08a"))))
text_yellow_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fde047"))))
text_yellow_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#facc15"))))
text_yellow_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#eab308"))))
text_yellow_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ca8a04"))))
text_yellow_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#a16207"))))
text_yellow_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#854d0e"))))
text_yellow_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#713f12"))))
text_yellow_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#422006"))))

text_lime_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f7fee7"))))
text_lime_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ecfccb"))))
text_lime_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#d9f99d"))))
text_lime_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#bef264"))))
text_lime_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#a3e635"))))
text_lime_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#84cc16"))))
text_lime_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#65a30d"))))
text_lime_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#4d7c0f"))))
text_lime_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#3f6212"))))
text_lime_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#365314"))))
text_lime_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#1a2e05"))))

text_green_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f0fdf4"))))
text_green_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#dcfce7"))))
text_green_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#bbf7d0"))))
text_green_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#86efac"))))
text_green_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#4ade80"))))
text_green_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#22c55e"))))
text_green_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#16a34a"))))
text_green_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#15803d"))))
text_green_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#166534"))))
text_green_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#14532d"))))
text_green_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#052e16"))))

text_emerald_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ecfdf5"))))
text_emerald_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#d1fae5"))))
text_emerald_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#a7f3d0"))))
text_emerald_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#6ee7b7"))))
text_emerald_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#34d399"))))
text_emerald_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#10b981"))))
text_emerald_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#059669"))))
text_emerald_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#047857"))))
text_emerald_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#065f46"))))
text_emerald_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#064e3b"))))
text_emerald_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#022c22"))))

text_teal_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f0fdfa"))))
text_teal_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ccfbf1"))))
text_teal_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#99f6e4"))))
text_teal_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#5eead4"))))
text_teal_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#2dd4bf"))))
text_teal_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#14b8a6"))))
text_teal_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#0d9488"))))
text_teal_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#0f766e"))))
text_teal_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#115e59"))))
text_teal_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#134e4a"))))
text_teal_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#042f2e"))))

text_cyan_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ecfeff"))))
text_cyan_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#cffafe"))))
text_cyan_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#a5f3fc"))))
text_cyan_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#67e8f9"))))
text_cyan_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#22d3ee"))))
text_cyan_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#06b6d4"))))
text_cyan_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#0891b2"))))
text_cyan_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#0e7490"))))
text_cyan_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#155e75"))))
text_cyan_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#164e63"))))
text_cyan_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#083344"))))

text_sky_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f0f9ff"))))
text_sky_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#e0f2fe"))))
text_sky_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#bae6fd"))))
text_sky_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#7dd3fc"))))
text_sky_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#38bdf8"))))
text_sky_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#0ea5e9"))))
text_sky_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#0284c7"))))
text_sky_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#0369a1"))))
text_sky_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#075985"))))
text_sky_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#0c4a6e"))))
text_sky_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#082f49"))))

text_blue_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#eff6ff"))))
text_blue_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#dbeafe"))))
text_blue_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#bfdbfe"))))
text_blue_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#93c5fd"))))
text_blue_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#60a5fa"))))
text_blue_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#3b82f6"))))
text_blue_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#2563eb"))))
text_blue_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#1d4ed8"))))
text_blue_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#1e40af"))))
text_blue_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#1e3a8a"))))
text_blue_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#172554"))))

text_indigo_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#eef2ff"))))
text_indigo_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#e0e7ff"))))
text_indigo_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#c7d2fe"))))
text_indigo_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#a5b4fc"))))
text_indigo_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#818cf8"))))
text_indigo_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#6366f1"))))
text_indigo_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#4f46e5"))))
text_indigo_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#4338ca"))))
text_indigo_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#3730a3"))))
text_indigo_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#312e81"))))
text_indigo_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#1e1b4b"))))

text_violet_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f5f3ff"))))
text_violet_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ede9fe"))))
text_violet_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ddd6fe"))))
text_violet_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#c4b5fd"))))
text_violet_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#a78bfa"))))
text_violet_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#8b5cf6"))))
text_violet_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#7c3aed"))))
text_violet_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#6d28d9"))))
text_violet_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#5b21b6"))))
text_violet_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#4c1d95"))))
text_violet_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#2e1065"))))

text_purple_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#faf5ff"))))
text_purple_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f3e8ff"))))
text_purple_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#e9d5ff"))))
text_purple_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#d8b4fe"))))
text_purple_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#c084fc"))))
text_purple_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#a855f7"))))
text_purple_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#9333ea"))))
text_purple_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#7e22ce"))))
text_purple_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#6b21a8"))))
text_purple_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#581c87"))))
text_purple_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#3b0764"))))

text_fuchsia_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fdf4ff"))))
text_fuchsia_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fae8ff"))))
text_fuchsia_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f5d0fe"))))
text_fuchsia_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f0abfc"))))
text_fuchsia_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#e879f9"))))
text_fuchsia_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#d946ef"))))
text_fuchsia_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#c026d3"))))
text_fuchsia_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#a21caf"))))
text_fuchsia_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#86198f"))))
text_fuchsia_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#701a75"))))
text_fuchsia_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#4a044e"))))

text_pink_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fdf2f8"))))
text_pink_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fce7f3"))))
text_pink_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fbcfe8"))))
text_pink_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f9a8d4"))))
text_pink_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f472b6"))))
text_pink_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ec4899"))))
text_pink_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#db2777"))))
text_pink_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#be185d"))))
text_pink_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#9d174d"))))
text_pink_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#831843"))))
text_pink_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#500724"))))

text_rose_50 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fff1f2"))))
text_rose_100 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#ffe4e6"))))
text_rose_200 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fecdd3"))))
text_rose_300 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fda4af"))))
text_rose_400 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#fb7185"))))
text_rose_500 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#f43f5e"))))
text_rose_600 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#e11d48"))))
text_rose_700 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#be123c"))))
text_rose_800 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#9f1239"))))
text_rose_900 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#881337"))))
text_rose_950 = Style(text=Text(style=CellStyle(foreground=Color.from_hex("#4c0519"))))

# Stop generated Tailwind colors


ml_auto = Style(margin=Margin(left="auto"))
mr_auto = Style(margin=Margin(right="auto"))
mx_auto = Style(margin=Margin(left="auto", right="auto"))
