name: publish-package

on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.repository.name }}
    permissions:
      contents: read  # add default back in
      id-token: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v4.1.7
    - name: Set up Python 3.x
      uses: actions/setup-python@v5.1.1
      with:
        python-version: "3.x"
    - name: Install Poetry
      uses: snok/install-poetry@v1.3.4
    - name: Build the package
      run: poetry build -vvv
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@v1.9.0
