name: publish-package

on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.repository.name }}
    permissions:
      id-token: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v3.5.2
    - name: Set up Python 3.x
      uses: actions/setup-python@v4.6.0
      with:
        python-version: "3.x"
    - name: Install Poetry
      uses: snok/install-poetry@v1.3.3
    - name: Build the package
      run: poetry build -vvv
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@v1.8.6
