name: publish-package

on:
  release:
    types: [published]

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.event.repository.name }}
    permissions:
      contents: read  # add default back in
      id-token: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v5.0.0
    - name: Install uv
      uses: astral-sh/setup-uv@v6.4.3
      with:
        enable-cache: true
    - name: Build the package
      run: uv build -vvv
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.4
