name: quality-check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-code:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: ["3.11", "3.12"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 15
    env:
      PLATFORM: ${{ matrix.platform }}
      PYTHON_VERSION: ${{ matrix.python-version }}
      PYTHONUTF8: 1  # https://peps.python.org/pep-0540/
      COLORTERM: truecolor
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
      - name: Install Package
        run: poetry install
      - name: Run pre-commit checks
        run: poetry run pre-commit run --all-files --show-diff-on-failure --color=always
      - name: Make sure we can build the package
        run: poetry build -vvv
      - name: Test types
        run: poetry run mypy
      - name: Test code
        run: poetry run pytest -v --cov --cov-report=xml --durations=20
      - name: Test docs
        run: poetry run mkdocs build --clean --strict --verbose
      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          env_vars: PLATFORM,PYTHON_VERSION
          fail_ci_if_error: false
